BEGIN;
----
REVOKE ALL PRIVILEGES ON SCHEMA bluth_co FROM veneer_app;
GRANT USAGE ON SCHEMA bluth_co TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA bluth_co
  REVOKE ALL
  ON SEQUENCES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA bluth_co
  GRANT UPDATE,SELECT
  ON SEQUENCES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL SEQUENCES
  IN SCHEMA bluth_co
  FROM veneer_app;
GRANT UPDATE,SELECT
  ON ALL SEQUENCES
  IN SCHEMA bluth_co
  TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA bluth_co
  REVOKE ALL
  ON TABLES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA bluth_co
  GRANT UPDATE,SELECT,DELETE,INSERT
  ON TABLES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL TABLES
  IN SCHEMA bluth_co
  FROM veneer_app;
GRANT UPDATE,SELECT,DELETE,INSERT
  ON ALL TABLES
  IN SCHEMA bluth_co
  TO veneer_app;
----
REVOKE ALL PRIVILEGES ON SCHEMA cyberdyne FROM veneer_app;
GRANT USAGE ON SCHEMA cyberdyne TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA cyberdyne
  REVOKE ALL
  ON SEQUENCES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA cyberdyne
  GRANT UPDATE,SELECT
  ON SEQUENCES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL SEQUENCES
  IN SCHEMA cyberdyne
  FROM veneer_app;
GRANT UPDATE,SELECT
  ON ALL SEQUENCES
  IN SCHEMA cyberdyne
  TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA cyberdyne
  REVOKE ALL
  ON TABLES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA cyberdyne
  GRANT UPDATE,SELECT,DELETE,INSERT
  ON TABLES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL TABLES
  IN SCHEMA cyberdyne
  FROM veneer_app;
GRANT UPDATE,SELECT,DELETE,INSERT
  ON ALL TABLES
  IN SCHEMA cyberdyne
  TO veneer_app;
----
REVOKE ALL PRIVILEGES ON SCHEMA initech FROM veneer_app;
GRANT USAGE ON SCHEMA initech TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA initech
  REVOKE ALL
  ON SEQUENCES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA initech
  GRANT UPDATE,SELECT
  ON SEQUENCES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL SEQUENCES
  IN SCHEMA initech
  FROM veneer_app;
GRANT UPDATE,SELECT
  ON ALL SEQUENCES
  IN SCHEMA initech
  TO veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA initech
  REVOKE ALL
  ON TABLES
  FROM veneer_app;
ALTER DEFAULT PRIVILEGES
  FOR ROLE veneer_admin
  IN SCHEMA initech
  GRANT UPDATE,SELECT,DELETE,INSERT
  ON TABLES
  TO veneer_app;
REVOKE ALL PRIVILEGES
  ON ALL TABLES
  IN SCHEMA initech
  FROM veneer_app;
GRANT UPDATE,SELECT,DELETE,INSERT
  ON ALL TABLES
  IN SCHEMA initech
  TO veneer_app;
----
COMMIT;
